name: Running
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Running
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build As Debug
        run: .github/test_app.sh
      
